# Generated by Django 3.2.9 on 2021-12-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('request_method', models.CharField(max_length=10)),
                ('request_path', models.CharField(max_length=500)),
                ('response_status', models.IntegerField()),
                ('request_body', models.JSONField()),
                ('remote_address', models.CharField(max_length=100)),
                ('server_hostname', models.CharField(max_length=100)),
                ('run_time', models.DecimalField(decimal_places=10, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'request_loggs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
