# Generated by Django 3.2.9 on 2021-12-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_log',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
